chainID: "Polkadot"
host: "0.0.0.0"
logLevel: "info"
network: "Polkadot"
proxy_port: ":3000"
worker_port: ":8087"
proxy:
  client:
    url: "localhost:50051" # polkadot-proxy url
indexer:
  client:
    page: 100
  manager:
    address: "127.0.0.1:8085"